### ISSUE TITLE
Does my IDE finds that subscription query implementation is missing?

### ISSUE THREAD

**Issue by adriatic** [generalui/redwood-stripe#10]
> Your IDE should see that the subscription query implementation is missing (at least VS Code does for me...), you can let your IDE create the skeleton implementation for this query for you, or create a file `api/src/services/subscriptions/subscriptions.ts` and add the content that retrieve the list of subscription, this is very similar to our seeder earlier

My IDE (vscode) does not see, so I had to write that query implementation:

```ts
import Stripe from 'stripe'
import { stripe } from 'src/lib/stripe'

export const subscriptions = async () => {
  // Get a list of active products
  const { data: products } = await stripe.products.list({
    active: true,
  })

  // Return the list of objects as defined in the sdl
  return products.map((p) => ({
    id: p.id,
    name: p.name,
    description: p.description,
    price: (p.default_price as Stripe.Price).unit_amount,
    currency: (p.default_price as Stripe.Price).currency,
  }))
```

**Comment by standup75** [comment]
Yes, that is unrelated to this project. But I would try reloading VS-Code, looking in the redwood tutorial if there's anything about setting the IDE correctly or reaching out to redwood community to try and see why your intellisense is off
