### ISSUE TITLE
Something changed in RedwoodJS, since you updated the code with my initial set of issues.

### ISSUE THREAD

**Issue by adriatic** [generalui/redwood-stripe#13]
### Summary
This seems like a recent Redwood error - unless I am confused. Please to run the sequence of commands up top and not included [Seller signup](https://github.com/generalui/redwood-stripe/tree/main/part1#seller-signup) section and let me know if you get the same error. In that case I will handle it further with Redwood guys - unless of course if you find what's going on

### Details

I started building the app from scratch as described in [README.md](https://github.com/generalui/redwood-stripe/tree/main/part1#readme). Everything went fine up to the [Seller signup](https://github.com/generalui/redwood-stripe/tree/main/part1#seller-signup) section.

At that point, `yarn rw dev` result with the crash :

```
nik$ yarn rw dev
/Users/nik/dev/work/redwood/rw-community/stripe/my-generalui/redwood-stripe/node_modules/@prisma/client/runtime/index.js:44703
            throw new PrismaClientInitializationError(error2.message, this.config.clientVersion, error2.error_code);
                  ^
PrismaClientInitializationError: error: Error validating datasource `db`: the URL must start with the protocol `file:`.
  -->  schema.prisma:3
   | 
 2 |   provider = "sqlite"
 3 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1
    at LibraryEngine.loadEngine (/Users/nik/dev/work/redwood/rw-community/stripe/my-generalui/redwood-stripe/node_modules/@prisma/client/runtime/index.js:44703:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async LibraryEngine.instantiateLibrary (/Users/nik/dev/work/redwood/rw-community/stripe/my-generalui/redwood-stripe/node_modules/@prisma/client/runtime/index.js:44632:5) {
  clientVersion: '3.15.2',
  errorCode: 'P1012'
}
```

Note that the error was reported from deep inside `node-modules` and that it "complains" about the  (original) schema.prisma

```
my-generalui/redwood-stripe/node_modules/@prisma/client/runtime/index.js:44703
            throw new PrismaClientInitializationError(error2.message, this.config.clientVersion, error2.error_code);

my schema.prisma at this point is of course
```
datasource db {
  provider = "postgres"
  url      = env("DATABASE_URL")
}

enum SubscriptionStatus {
  init
  success
  failed
}

model User {
  id                  Int                 @id @default(autoincrement())
  email               String              @unique
  hashedPassword      String
  salt                String
  roles               String[]
  stripeClientSecret  String?
  resetToken          String?
  resetTokenExpiresAt DateTime?
  subscriptionName    String?
  subscriptionStatus  SubscriptionStatus?
}

```

**Comment by standup75** [comment]
The error shows `provider = "sqlite"` but you seem to have `provider = "postgres"` something doesn't match there

**Comment by adriatic** [comment]
It's not that simple, Stan - there should be no trace of "sqlite" anywhere in my environment. This data is fetched at `/Users/nik/dev/work/redwood/rw-community/stripe/my-generalui/redwood-stripe/node_modules/@prisma/client/runtime/index.js:44703`

What business has my app at `@prisma/client/runtime/index.js:44703` ??

I will reset the postgres database which was created at the time I run the tutorial first time (week ago), as I am not sure whether i can reuse that database when creating the "redwood-stripe" from scratch again.

The app creation results with:

> After we add our first database table there will also be a SQLite database file named dev.db and a directory called migrations created for us. migrations contains the files that act as snapshots of the database schema changing over time.

I will find out the whole "life cycle" of the database for the postgres case  when the first step `yarn create redwood-app ./redwoodblog` creates the mysql database - not postgres. While editing schema.prisma is not a big deal, the `yarn create ...` should take the database type as an argument; this what we have today is a bug.
