### ISSUE TITLE
Reseting the database?

### ISSUE THREAD

**Issue by adriatic** [generalui/redwood-stripe#15]
Does the postgres database need to reset (to empty), when the app is built again from scratch, by running:

`yarn create redwood-app --ts ./redwood-stripe`

Alternatively, is this [issue](https://github.com/generalui/redwood-stripe/issues/13) a consequence of not resetting the database first?

**Comment by standup75** [comment]
I'm not sure, it shouldn't be necessary imho, but you can use `yarn rw prisma migrate reset` to reset the db, it doesn't hurt

**Comment by adriatic** [comment]
In order to facilitate a clean regeneration of the app:

1. Deleted redwood-app folder
2. Run `yarn create redwood-app --ts ./redwood-stripe` and `yarn rw setup ui tailwindcss`
3. Edited the just generated prisma.schema to set the provider to be `postgres`, and define the rest of required data
4. Created the .env file with all needed information
5. Run `yarn rw prisma migrate reset` - resulting with
```
Running Prisma CLI...
$ yarn prisma migrate reset --schema /Users/nik/dev/work/redwood/rw-community/stripe/my-generalui/redwood-stripe/api/db/schema.prisma

Environment variables loaded from .env
Prisma schema loaded from api/db/schema.prisma
Datasource "db": PostgreSQL database "redwoodstripe", schema "public" at "localhost:5432"

✔ Are you sure you want to reset your database? All data will be lost. … yes

Database reset successful


✔ Generated Prisma Client (3.15.2 | library) to ./node_modules/@pr
isma/client in 98ms

Running seed command `yarn rw exec seed` ...
[11:41:47] Generating Prisma client [started]
[11:41:47] Generating Prisma client [completed]
[11:41:47] Running script [started]

Using the default './scripts/seed.{js,ts}' template
Edit the file to add seed data

[11:41:48] Running script [completed]

🌱  The seed command has been executed.
```

Note that resetting the database using RedwoodJS generator has all kind of side effects.
