### ISSUE TITLE
Two fields missing in the part1 readme.md

### ISSUE THREAD

**Issue by adriatic** [generalui/redwood-stripe#17]
The two fields are ` CheckboxField`, and `EmailField`, in the [README.md](https://github.com/generalui/redwood-stripe/blob/main/part1/readme.md) file, section [seller signup](https://github.com/generalui/redwood-stripe/tree/main/part1#seller-signup).

**Comment by standup75** [comment]
hmm, I don't see what is missing here

**Comment by adriatic** [comment]
I mean that the two fields in the yellow rectangle are not present in the code for SignupPage as initially created.

<img width="481" alt="image" src="https://user-images.githubusercontent.com/2712405/181920838-f0a37b57-b4ca-4518-8c6f-37e6fb768c0f.png">

**Note** that this issue may be gone by some of the changes. I will keep a flag to check whether the final version is OK

**Comment by standup75** [comment]
Per my previous, I would not always update the import if I add something to a file, it would really clutter the tutorial, and those can be completed by VS Code

**Comment by adriatic** [comment]
### Warning
You stated to be inclined not to document import file - which I agreed. In this case two fields, are missing in an existing import statement. As you are the boss, I will agree with you, but if I was the boss I would not leave known puzzles in the documentation. In my view such approach indicates "laziness"
