### ISSUE TITLE
Missing import declarations

### ISSUE THREAD

**Issue by adriatic** [generalui/redwood-stripe#19]
Context: `https://github.com/generalui/redwood-stripe/blob/main/part1/scripts/seed-stripe-subscriptions.ts`

---

Missing:
```
import Stripe from 'stripe'
import { stripe } from 'api/src/lib/stripe'
```

To be precise these two import statements are present in the next code section of the code in this script.

**Comment by standup75** [comment]
I don't understand this one, everything looks right to me

**Comment by adriatic** [comment]
**context:** https://github.com/generalui/redwood-stripe/tree/main/part1#add-some-subscription-products

This code is being defined in a several sections of the README.md file, so the import declarations, should be defined in the first section, right after the text:

```
We first define our subscriptions as a list of Stripe.ProductCreateParams
```

The final definition of the `seed-stripe-subscriptions` script is complete - I just got confused for a while not seeing the import statement at the top of the script.

**Comment by standup75** [comment]
Ok, I moved them, moving forward let's try to not add all import statements. If some are missing, I think it's ok, your IDE should be able to complete them for you, or you can always look up the source code.

**Comment by adriatic** [comment]
Agreed
