### ISSUE TITLE
Automatic creation of the skeleton file api/src/services/subscriptions/subscriptions.ts

### ISSUE THREAD

**Issue by adriatic** [generalui/redwood-stripe#20]
The statement:

> Your IDE should see that the subscription query implementation is missing (at least VS Code does for me...), you can let your IDE create the skelton implementation for this query for you, or create a file api/src/services/subscriptions/subscriptions.ts

is not happening for me:

<img width="321" alt="image" src="https://user-images.githubusercontent.com/2712405/181110802-37bb1e7c-fcc8-45f6-8ab3-3d38343ed6b3.png">

Made this screenshot after running the app with `yarn rw dev` - so please explain the conditions that resulted with the seleton `api/src/services/subscriptions/subscriptions.ts` file.

Also, please fix the "skelton" typo above

**Comment by standup75** [comment]
What I meant by "let your IDE..." is to right click on the error and take the suggested action.
Fixed skeleton, thanks
