### ISSUE TITLE
extra item in SubscriptionsCell.tsx

### ISSUE THREAD

**Issue by adriatic** [generalui/redwood-stripe#21]
In the section [Create a page to choose a subscription](https://github.com/generalui/redwood-stripe/tree/main/part1#create-a-page-to-choose-a-subscription), second code section  the `priceId` item is extraneous

<img width="414" alt="image" src="https://user-images.githubusercontent.com/2712405/181373562-c9a8e2da-7b64-4d58-93c8-d2a1fbc5f5f1.png">

**Comment by standup75** [comment]
absolutely, removed
