### ISSUE TITLE
File SubscriptionCell.tsx too many errors to define here

### ISSUE THREAD

**Issue by adriatic** [generalui/redwood-stripe#22]
The errors are in the https://github.com/generalui/redwood-stripe/tree/main/part1#create-a-page-to-choose-a-subscription document, not the actual code.

I suggest to simply take a copy of the code and paste it in this section of the [README.md](https://github.com/generalui/redwood-stripe/tree/main/part1#readme)

**Comment by standup75** [comment]
Thanks, I think I just left a bit too much code in that first stab at writing the cell, I removed some code so that it feels really progressive.
