### ISSUE TITLE
A typo in create-a-page-to-choose-a-subscription

### ISSUE THREAD

**Issue by adriatic** [generalui/redwood-stripe#23]
#### Context:

[create-a-page-to-choose-a-subscription](https://github.com/generalui/redwood-stripe/tree/main/part1#create-a-page-to-choose-a-subscription)

<img width="755" alt="image" src="https://user-images.githubusercontent.com/2712405/181854610-071d82cd-d5c1-4d57-8306-6e4286ff8a16.png">

Left arrow points to the place where the 'dot' needs to replaced by a 'dash. The right arrow points to the capital A, that needs to be a lowercase a

**Comment by standup75** [comment]
ok
