### ISSUE TITLE
Synchronizing environments

### ISSUE THREAD

**Issue by adriatic** [generalui/redwood-stripe#4]
**Summary: this issue indicates with incorrect declarations in the DOCS (like provider="sqlite"), which mark the use of `enum` as not allowed** 

---

A couple of observed differences, discovered while following [prerequisites](https://github.com/generalui/redwood-stripe/tree/main/part1#prerequistes) - (_this last word is misspelled in your repo_)

<img width="751" alt="image" src="https://user-images.githubusercontent.com/2712405/179368406-ff55d37d-037b-4d9e-aa38-de60f244f28e.png">

The problem with roles is defined as 

`Field "roles" in model "User" can't be a list. The current connector does not support lists of primitive types.`

My environment as reported by `yarn info` command is listed in the next section below (so it wouldn't disrupt the current flow of text.

Without going any further, here are my questions

## 1.
I am not using `nvm` - and will switch to your suggested use (to be able to subsequently test this app with different node version (at the moment, my globally installed node **is** v16.5.1)
```
nvm install v16.15.1
nvm alias default v16.15.1
nvm use v16.15.1
```
Any suggestions on changing anything so far?

## 2.

I have PostgreSQL database installed locally

<img width="750" alt="image" src="https://user-images.githubusercontent.com/2712405/179369167-521afcc6-b8f7-4b4e-bda2-be2f3b94bb3b.png">

and would prefer to use it (rather then to use the dockerized version) as it will provide a slightly different test. Do you agree?

**I will wait to see your responses before continue building your app locally**

**Comment by adriatic** [comment]
### yarn info output

```
nik$ yarn info
├─ @redwoodjs/core@npm:2.1.0
│  ├─ Version: 2.1.0
│  │
│  ├─ Exported Binaries
│  │  ├─ cross-env
│  │  ├─ eslint
│  │  ├─ jest
│  │  ├─ nodemon
│  │  ├─ redwood
│  │  ├─ rimraf
│  │  ├─ rw
│  │  ├─ rw-api-server-watch
│  │  ├─ rw-gen
│  │  ├─ rw-gen-watch
│  │  ├─ rw-log-formatter
│  │  └─ rwfw
│  │
│  └─ Dependencies
│     ├─ @babel/core@npm:7.16.7 → npm:7.16.7
│     ├─ @babel/runtime-corejs3@npm:7.16.7 → npm:7.16.7
│     ├─ @redwoodjs/cli@npm:2.1.0 → npm:2.1.0
│     ├─ @redwoodjs/eslint-config@npm:2.1.0 → npm:2.1.0
│     ├─ @redwoodjs/internal@npm:2.1.0 → npm:2.1.0
│     ├─ @redwoodjs/testing@npm:2.1.0 → npm:2.1.0
│     ├─ babel-plugin-auto-import@npm:1.1.0 → npm:1.1.0
│     ├─ babel-plugin-module-resolver@npm:4.1.0 → npm:4.1.0
│     ├─ babel-timing@npm:0.9.1 → npm:0.9.1
│     ├─ core-js@npm:3.23.3 → npm:3.23.3
│     ├─ esbuild@npm:0.14.48 → npm:0.14.48
│     ├─ fast-glob@npm:3.2.11 → npm:3.2.11
│     ├─ graphql@npm:16.5.0 → npm:16.5.0
│     ├─ lodash.escaperegexp@npm:4.1.2 → npm:4.1.2
│     ├─ nodemon@npm:2.0.19 → npm:2.0.19
│     ├─ react-refresh@npm:0.13.0 → npm:0.13.0
│     ├─ rimraf@npm:3.0.2 → npm:3.0.2
│     ├─ svg-react-loader@npm:0.4.6 → npm:0.4.6
│     ├─ typescript@patch:typescript@4.7.3#~builtin<compat/typescript> → patch:typescript@npm%3A4.7.3#~builtin<compat/typescript>::version=4.7.3&hash=7ad353
│     ├─ webpack-bundle-analyzer@npm:4.5.0 → npm:4.5.0
│     ├─ webpack-merge@npm:5.8.0 → npm:5.8.0
│     ├─ @babel/cli@npm:7.16.7 → npm:7.16.7 [f0093]
│     ├─ @babel/eslint-plugin@npm:7.16.5 → npm:7.16.5 [f0093]
│     ├─ @babel/node@npm:7.16.7 → npm:7.16.7 [f0093]
│     ├─ @babel/plugin-proposal-class-properties@npm:7.16.7 → npm:7.16.7 [f0093]
│     ├─ @babel/plugin-proposal-decorators@npm:7.16.7 → npm:7.16.7 [f0093]
│     ├─ @babel/plugin-proposal-private-methods@npm:7.16.7 → npm:7.16.7 [f0093]
│     ├─ @babel/plugin-proposal-private-property-in-object@npm:7.16.7 → npm:7.16.7 [f0093]
│     ├─ @babel/plugin-transform-runtime@npm:7.16.7 → npm:7.16.7 [f0093]
│     ├─ @babel/preset-env@npm:7.16.7 → npm:7.16.7 [f0093]
│     ├─ @babel/preset-react@npm:7.16.7 → npm:7.16.7 [f0093]
│     ├─ @babel/preset-typescript@npm:7.16.7 → npm:7.16.7 [f0093]
│     ├─ @pmmmwh/react-refresh-webpack-plugin@npm:0.5.7 → npm:0.5.7 [f0093]
│     ├─ babel-loader@npm:8.2.3 → npm:8.2.3 [f0093]
│     ├─ babel-plugin-graphql-tag@npm:3.3.0 → npm:3.3.0 [f0093]
│     ├─ babel-plugin-inline-react-svg@npm:2.0.1 → npm:2.0.1 [f0093]
│     ├─ copy-webpack-plugin@npm:11.0.0 → npm:11.0.0 [f0093]
│     ├─ css-loader@npm:6.7.1 → npm:6.7.1 [f0093]
│     ├─ css-minimizer-webpack-plugin@npm:4.0.0 → npm:4.0.0 [f0093]
│     ├─ dotenv-webpack@npm:7.1.0 → npm:7.1.0 [f0093]
│     ├─ esbuild-loader@npm:2.19.0 → npm:2.19.0 [f0093]
│     ├─ file-loader@npm:6.2.0 → npm:6.2.0 [f0093]
│     ├─ graphql-tag@npm:2.12.6 → npm:2.12.6 [812e4]
│     ├─ html-webpack-plugin@npm:5.5.0 → npm:5.5.0 [f0093]
│     ├─ mini-css-extract-plugin@npm:2.6.0 → npm:2.6.0 [f0093]
│     ├─ null-loader@npm:4.0.1 → npm:4.0.1 [f0093]
│     ├─ style-loader@npm:3.3.1 → npm:3.3.1 [f0093]
│     ├─ url-loader@npm:4.1.1 → npm:4.1.1 [f0093]
│     ├─ webpack-cli@npm:4.10.0 → npm:4.10.0 [f0093]
│     ├─ webpack-dev-server@npm:4.9.2 → npm:4.9.2 [f0093]
│     ├─ webpack-manifest-plugin@npm:5.0.0 → npm:5.0.0 [f0093]
│     ├─ webpack-retry-chunk-load-plugin@npm:3.1.1 → npm:3.1.1 [f0093]
│     └─ webpack@npm:5.73.0 → npm:5.73.0 [f0093]
│
└─ root-workspace-0b6124@workspace:.
   ├─ Version: 0.0.0
   │
   └─ Dependencies
      └─ @redwoodjs/core@npm:2.1.0 → npm:2.1.0

```

**Comment by standup75** [comment]
Your datasource provider still says `sqlite`, change this to `postgres`

**Comment by standup75** [comment]
You can use a local instance or a dockerized instance of pg, I don't have any preference

**Comment by adriatic** [comment]
> Your datasource provider still says sqlite, change this to postgres

How did get this conclusion? My local clone has all the changes (reported via these [issues](https://github.com/generalui/redwood-stripe/issues)) already in place - as I knew without your feedback, how to fix them. I just did not want to impose them on you via PR's.

Now, once seeing how you handle reports from someone you never worked with, I will proceed with generating PR's
