### ISSUE TITLE
vscode indicates problems in launch.json

### ISSUE THREAD

**Issue by adriatic** [generalui/redwood-stripe#5]
Both underlined strings have same problem

<img width="640" alt="image" src="https://user-images.githubusercontent.com/2712405/179370869-248dafe8-1105-4899-8f3f-108c18c152d7.png">

The closest issue I found is [Confusing "Property is not allowed" error, when property is allowed, just slightly misconfigured](https://github.com/redhat-developer/vscode-yaml/issues/614)

**Comment by standup75** [comment]
Ok, this is irrelevant to this tutorial, I removed the file
