### ISSUE TITLE
provider declared incorrectly - by default

### ISSUE THREAD

**Issue by adriatic** [generalui/redwood-stripe#6]
The [Authentication](https://github.com/generalui/redwood-stripe/tree/main/part1#authentication) section of the README.md file needs to add the redefined `datasource` structure to be:
```
datasource db {
  provider = "postgres"
  url      = env("DATABASE_URL")
}
```
the provider field is by default defined as `sqlite`. Without this change  both `enum` declaration and field `roles     String[]` are marked as invalid.

Note: the actual code is fine - just the documentation needs to be fixed.

**Comment by standup75** [comment]
added
