### ISSUE TITLE
Replace the environment variables management with Doppler.

### ISSUE THREAD

**Issue by adriatic** [generalui/redwood-stripe#7]
Check [Doppler](https://www.doppler.com/) and note the scalability of this approach.

**Comment by standup75** [comment]
That looks cool, but overkill for the scope of this tutorial imho

**Comment by adriatic** [comment]
> That looks cool, but overkill for the scope of this tutorial imho.

Cannot disagree - this app is the closest of RedwoodJS sample applications that has enough "meat on the bones" to illustrate the use of Doppler. This is of course your call and I appreciate your focus on Stripe.
