### ISSUE TITLE
Two fields from @redwoodjs/forms missing in README.md

### ISSUE THREAD

**Issue by adriatic** [generalui/redwood-stripe#8]
These two fields pointed to by [this reference](https://github.com/generalui/redwood-stripe/blob/main/part1/web/src/pages/SignupPage/SignupPage.tsx#L9-L10) are not present in [this](https://github.com/generalui/redwood-stripe/tree/main/part1#seller-signup) section of the README.md document.

**Comment by standup75** [comment]
That's a good point, but it is a choice I made to not always include the imports inside the readme, it clutters the explanations unnecessarily, and IDE is helping with importing, and you can always look up the source code

**Comment by adriatic** [comment]
I would suggest to enumerate such choices you made at the very beginning of the documentation. This would save some pedantic soul to become worried how could this code (as described in the docs) actually compile.

Whenever you see that I am too worried about the clarify of the documentation, please stop me (from worrying)
